baseURL = 'https://github.io/schudlich/stoutheartpress/'
locale = 'en-us'
title = 'Stout Heart Press'
copyright = '2026, Tanner Schudlich'
enableRobotsTXT= true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[markup.goldmark.renderer]
unsafe = true

[params]
bookLogo = "littlelogo.png"
BookToC = false
bookFavicon = "littlelogo.png"
bookSection = "docs"