baseURL = 'https://github.io/schudlich/stoutheartpress/'
locale = 'en-us'
title = 'Stout Heart Press'
copyright = '2026, Tanner Schudlich'


[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
bookLogo = "littlelogo.png"
[menu]
[[home]]
name = "About"
pageRef = "content/about/_index.md/"
weight= 1
